config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'

  resources :geofences, only: %i(show new create edit update destroy) do
    get 'all', on: :collection
  end

  resources :timetracks, only: %i(show new create) do
    get 'all', on: :collection
    get 'location', on: :collection
  end

  post 'timetracks/register-location', to: 'timetracks#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geofence.rb
class Geofence < ApplicationRecord
  validates :description, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :radius, presence: true

  has_many :timetracks

  def self.check_timetrack_location(timetrack)
    Geofence.all.select do |geofence|
      distance = Haversine.distance(geofence.latitude, geofence.longitude,
                                    timetrack.latitude, timetrack.longitude)
      geofence.radius >= distance.to_km
    end
  end
end

app/models/timetrack.rb
class Timetrack < ApplicationRecord
  belongs_to :geofence

  validates :user, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validate :check_placement, if: :latitude_and_longitude_present?

  private

  def latitude_and_longitude_present?
    true unless latitude.nil? || longitude.nil?
  end

  def check_placement
    distance = Haversine.distance(geofence.latitude,
                                  geofence.longitude,
                                  latitude, longitude)

    error_msg = 'Timetracks can only be registered inside Geofence area'
    errors.add(:base, error_msg) unless geofence.radius >= distance.to_km
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/geofences_controller.rb
class GeofencesController < ApplicationController
  def all
    @geofences = Geofence.all.order('id DESC')
  end

  def new
    @geofence = Geofence.new
  end

  def create
    @geofence = Geofence.new(geofence_params)
    if @geofence.save
      redirect_to @geofence, notice: 'Geofence successfully saved!'
    else
      render :new
    end
  end

  def show
    @geofence = Geofence.find(params[:id])
  end

  def edit
    @geofence = Geofence.find_by(id: params[:id])
  end

  def update
    @geofence = Geofence.find_by(id: params[:id])

    if @geofence.update(geofence_params)
      redirect_to @geofence, notice: 'Geofence successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    geofence = Geofence.find_by(id: params[:id])

    if geofence.destroy
      redirect_to all_geofences_path, notice: 'Geofence successfully removed'
    else
      redirect_to all_geofences_path, alert: 'Error: Geofence was not removed'
    end
  end

  private

  def geofence_params
    params.require(:geofence).permit(:description, :latitude,
                                     :longitude, :radius)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index; end
end

app/controllers/timetracks_controller.rb
class TimetracksController < ApplicationController
  def all
    @timetracks = Timetrack.all.order('id DESC')
  end

  def new
    @timetrack = Timetrack.new(timetrack_params)
    @geofences = Geofence.check_timetrack_location(@timetrack)

    error_msg = 'It doesn\'t have any Geofence near you...'
    @timetrack.errors.add(:base, error_msg) if @geofences.size.zero?
  end

  def show
    @timetrack = Timetrack.find_by(id: params[:id])
  end

  def location; end

  def register_location; end

  def create
    @timetrack = Timetrack.new(timetrack_params)
    if @timetrack.save
      redirect_to @timetrack, notice: 'Timetrack successfully saved!'
    else
      @geofences = Geofence.all
      render :new
    end
  end

  private

  def timetrack_params
    params.require(:timetrack).permit(:geofence_id, :user, :comment,
                                      :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/geofences/_form.html.erb
<div id="form-app">
  <% geofence.errors.full_messages.each do |msg| %>
    <div class="card-panel red accent-4 white-text">
      <i class="material-icons medium left">error</i>
      <p><%= msg %></p>
    </div>
  <% end %>
  <br>
  <p>Click on the map or insert in the form bellow</p>
  <br>
  <div id="map" @click="mapClicked" style="width: 100%; height: 400px;">
    <div class="progress" style="margin-top: 200px;">
        <div class="indeterminate"></div>
    </div>
  </div>
  <br>
  <%= form_with model: geofence, local: true, html: {'v-on:submit.stop': 'validatesForm'} do |f| %>
    <%= f.label :description, 'Description' %>
    <%= f.text_field :description, 'v-model': 'description' %>
    <%= f.label :latitude, 'Latitude' %>
    <%= f.text_field :latitude, 'v-model': 'latitude' %>
    <%= f.label :longitude, 'Longitude' %>
    <%= f.text_field :longitude, 'v-model': 'longitude' %>
    <%= f.label :radius, 'Radius (mt)' %>
    <%= f.number_field :radius, 'v-model': 'radius' %>
    <br>
    <div class="row">
    <br>
      <%= link_to all_geofences_path, class: 'btn-large waves-effect waves-light blue-grey lighten-4 black-text' do %>
        <i class="material-icons left">arrow_back</i> Back
      <% end %>
      &nbsp;
      <%= f.button type: 'submit', class: 'btn-large waves-effect waves-light red accent-2' do %>
        Submit
      <% end %>
    </div>

  <% end %>
  <ul v-if="messages.length">
    <li v-for="(msg, index) in messages" :key="index">
      <div class="card-panel red accent-4 white-text">
        <i class="material-icons medium left">error</i>
        <p>{{msg}}</p>
      </div>
    </li>
  </ul>
  <br><br><br>
</div>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>

<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
   integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
   crossorigin=""></script>

<script>
var formApp = new Vue({
  el: '#form-app',
  data: {
    description: '<%= geofence.description %>',
    latitude: '<%= geofence.latitude %>',
    longitude: '<%= geofence.longitude %>',
    radius: <%= geofence.radius || 0 %>,
    messages: [],
    map: null,
    tileLayer: null,
    layers: [],
    marker: null,
    circle: null
  },
  watch: {
    radius: function() {
      this.setFenceCircle()
    },
    latitude: function() {
      this.moveIntoMap()
    },
    longitude: function() {
      this.moveIntoMap()
    }
  },
  methods: {
    validatesForm(e) {
      this.messages.length = 0;

      if(this.description.trim() == '') {
        this.messages.push('Description can\'t be blank')
      }
      if(this.latitude.trim() == '') {
        this.messages.push('Latitude can\'t be blank')
      }
      if(this.longitude.trim() == '') {
        this.messages.push('Longitude can\'t be blank')
      }
      if(!this.radius) {
        this.messages.push('Radius can\'t be blank')
      }

      if(!this.messages.length){
        return true
      }

      e.preventDefault()
    },
    getUserPosition() {
      navigator.geolocation.getCurrentPosition(position => {
        this.latitude = position.coords.latitude
        this.longitude = position.coords.longitude
        this.initMap()
      }, error => {
        this.initMap()
      })
    },
    initMap() {
      const lat = this.latitude || -14.235
      const lng = this.longitude || -51.9253

      this.map = L.map('map').setView([lat, lng], 15)

      this.tileLayer = L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWF0aHZwIiwiYSI6ImNqeGx5dnU4OTA1d2EzdW8zM3F5YTkzOHYifQ.b-X2rJrUaVOk_qnMk2w9kQ', {
                          attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                          maxZoom: 20,
                          id: 'mapbox.streets',
                          accessToken: 'pk.eyJ1IjoibWF0aHZwIiwiYSI6ImNqeGx5dnU4OTA1d2EzdW8zM3F5YTkzOHYifQ.b-X2rJrUaVOk_qnMk2w9kQ'
                      })
      this.tileLayer.addTo(this.map)

      this.marker = L.marker([lat, lng]).addTo(this.map)

      this.setFenceCircle()
    },
    mapClicked() {
      this.map.on('click', this.onMapClick)
    },
    onMapClick(e) {
      this.map.panTo(e.latlng, 15)
      this.marker.setLatLng(e.latlng)
      this.latitude = e.latlng.lat
      this.longitude = e.latlng.lng

      if(this.circle) {
        this.circle.setLatLng([this.latitude, this.longitude])
      }
    },
    setFenceCircle() {
      if(this.radius && this.radius > 0){
        if(this.circle) {
          this.circle.setRadius(this.radius)
        } else {
          this.circle = L.circleMarker([this.latitude, this.longitude], {
              color: 'red',
              fillColor: '#f03',
              fillOpacity: 0.5,
              radius: this.radius
          }).addTo(this.map)
        }
      }

    },
    moveIntoMap() {
      this.map.panTo([this.latitude, this.longitude], 15)
      this.marker.setLatLng([this.latitude, this.longitude])

      if(this.circle) {
        this.circle.setLatLng([this.latitude, this.longitude])
      }
    }
  },
  mounted() {
    if(!this.latitude) {
      this.$nextTick(() => {
        this.getUserPosition()
      })
    } else {
      this.initMap()
    }
  }
})
</script>

app/views/geofences/all.html.erb
<div class="container">
<h1>Geofences</h1>

  <% if notice %>
    <div class="card-panel green accent-2 green-text text-darken-4">
      <i class="material-icons medium left">check_circle</i>
      <p class="flow-text"><%= notice %></p>
    </div>
    <br>
  <% end %>

  <div class="row">
    <p>Click on Geofence to see it on Map</p>
  </div>

  <div class="row">
    <% if @geofences.any? %>
      <table class="striped highlight responsive-table flow-text">
        <thead>
          <tr>
            <th>Description</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Radius (mt)</th>
            <th>Edit</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody>
          <% @geofences.each do |geofence| %>
            <tr>
              <td>
                <%= link_to geofence_path(geofence.id), class: 'blue-grey-text text-darken-3' do  %>
                  <%= geofence.description %>
                <% end %>
              </td>
              <td>
                <%= link_to geofence_path(geofence.id), class: 'blue-grey-text text-darken-3' do %>
                  <%= number_with_precision(geofence.latitude, precision: 10) %>
                <% end %>
              </td>
              <td>
                <%= link_to geofence_path(geofence.id), class: 'blue-grey-text text-darken-3' do %>
                  <%= number_with_precision(geofence.longitude, precision: 10) %>
                <% end %>
              </td>
              <td>
                <%= link_to geofence_path(geofence.id), class: 'blue-grey-text text-darken-3' do %>
                  <%= "#{number_with_precision(geofence.radius, precision: 2,  strip_insignificant_zeros: true)} mt" %>
                <% end %>
              </td>
              <td>
                <%= link_to edit_geofence_path(geofence.id), id: "edit-geo-#{geofence.id}", class: 'btn-floating waves-effect waves-light btn-small' do %>
                  <i class="material-icons left">edit</i>
                <% end %>
              </td>
              <td>
                <%= link_to geofence, method: :delete, id: "delete-geo-#{geofence.id}", class: 'delete btn-floating waves-effect waves-light btn-small red' do %>
                  <i class="material-icons center">delete</i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% else %>
        <p class="flow-text">Nothing found</p>
      <% end %>
    </div>
    <br>
    <div class="row">
      <%= link_to new_geofence_path, class: 'btn-large waves-effect waves-light red accent-2' do %>
        <i class="material-icons right">add</i> Add new Geofence
      <% end %>
    </div>
    <br><br>
</div>

<script>

</script>

app/views/geofences/edit.html.erb
<div class="container">
  <h1>Edit Geofence</h1>
  <%= render partial: 'form', locals: { geofence: @geofence } %>
</div>

app/views/geofences/new.html.erb
<div class="container">
  <h1>New Geofence</h1>

  <%= render partial: 'form', locals: { geofence: @geofence } %>
</div>

app/views/geofences/show.html.erb
<div class="container">
  <h1>Geofence '<%= @geofence.description %>'</h1>
  <% if notice %>
    <div class="card-panel green accent-2 green-text text-darken-4">
      <i class="material-icons medium left">check_circle</i>
      <p class="flow-text"><%= notice %></p>
    </div>
  <% end %>

  <div class="row">
    <div class="col s6">
      <table class="flow-text highlight responsive-table ">
        <tr>
          <td>Latitude:</td>
          <td><%= @geofence.latitude %></td>
        </tr>
        <tr>
          <td>Longitude</td>
          <td><%= @geofence.longitude %></td>
        </tr>
        <tr>
          <td>Radius</td>
          <td>
            <%= number_with_precision(@geofence.radius, precision: 2, strip_insignificant_zeros: true) %> mt
          </td>
        </tr>
      </table>
    </div>

    <div class="col s6">
      <div id="map" style="width: 600px; height: 400px;"></div>
    </div>
  </div>

  <br><br>
  <div class="row">
    <%= link_to all_geofences_path, class: 'btn-large waves-effect waves-light blue-grey lighten-4 black-text' do %>
      <i class="material-icons left">arrow_back</i> Back
    <% end %>
  </div>
  <br><br><br>

</div>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>

<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
   integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
   crossorigin=""></script>

<script>
  var mymap = L.map('map').setView([<%= @geofence.latitude %>, <%= @geofence.longitude %>], 15);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWF0aHZwIiwiYSI6ImNqeGx5dnU4OTA1d2EzdW8zM3F5YTkzOHYifQ.b-X2rJrUaVOk_qnMk2w9kQ', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 20,
      id: 'mapbox.streets',
      accessToken: 'pk.eyJ1IjoibWF0aHZwIiwiYSI6ImNqeGx5dnU4OTA1d2EzdW8zM3F5YTkzOHYifQ.b-X2rJrUaVOk_qnMk2w9kQ'
  }).addTo(mymap);

  var marker = L.marker([<%= @geofence.latitude %>, <%= @geofence.longitude %>]).addTo(mymap);

  var circle = L.circle([<%= @geofence.latitude %>, <%= @geofence.longitude %>], {
      color: 'red',
      fillColor: '#f03',
      fillOpacity: 0.5,
      radius: <%= @geofence.radius %>
  }).addTo(mymap);
</script>

app/views/index/index.html.erb
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center red-text text-accent-2">mywork challenge</h1>
      <div class="row center">
        <h5 class="header col s12 light">
          Select the option bellow for <strong>Manager</strong> or <strong>Employee</strong>:
        </h5>
      </div>
      <div class="row center">
        <%= link_to 'I\'m a Manager', all_geofences_path, class: 'btn-large waves-effect waves-light red accent-2' %>
        &nbsp;
        <%= link_to 'I\'m an Employee', all_timetracks_path, class: 'btn-large waves-effect waves-light red accent-2' %>
      </div>
      <br><br>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myworkChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
    <style>
    body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }
    main {
      flex: 1 0 auto;
    }
    </style>
  </head>
  <body>
    <nav class="red accent-2" role="navigation">
      <div class="nav-wrapper container">
        <%= link_to 'Timetrack', root_path, class: 'brand-logo', id: 'logo-container' %>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Geofences', all_geofences_path %></li>
          <li><%= link_to 'Timetracks', all_timetracks_path %></li>
          <li><%= link_to 'Register Timetrack', location_timetracks_path %></li>
        </ul>

        <ul id="nav-mobile" class="sidenav">
          <li><%= link_to 'Geofences', all_geofences_path %></li>
          <li><%= link_to 'Timetracks', all_timetracks_path %></li>
          <li><%= link_to 'Register Timetrack', location_timetracks_path %></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
    </nav>

    <main>
      <%= yield %>
    </main>

    <footer class="page-footer red accent-2">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Matheus Vieira</h5>
            <ul>
              <li>matheusvieiradepaula@gmail.com</li>
              <li><a class="white-text" href="https://github.com/mathvp" target="_blank">github.com/mathvp</a></li>
              <li><a class="white-text" href="https://www.linkedin.com/in/mathvp/" target="_blank">LinkedIn</a></li>
            </ul>
            <p class="grey-text text-lighten-4"></p>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container center-align">
          Made with Ruby on Rails | 2019
        </div>
      </div>
    </footer>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
      });
    </script>
  </body>
</html>

app/views/timetracks/_form.html.erb
<div id="form-app">
  <% timetrack.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <%= form_with model: timetrack, local: true, html: {'v-on:submit.stop': 'validatesForm'} do |f| %>
    <%= f.label :user, 'Username' %>
    <%= f.text_field :user, 'v-model': 'username' %>
    <%= f.label :geofence_id, 'Geofence' %>
    <!-- <%= f.select(:geofence_id,  options_from_collection_for_select(geofences.to_a, :id, :description)) %> -->
    <%= f.collection_select :geofence_id, geofences || [], :id, :description, { prompt:'Select Geofence' }, { class: 'browser-default', 'v-model':'geofence' }%>
    <%= f.label :comment, 'Comment' %>
    <%= f.text_area :comment %>
    <%= f.submit 'Register' %>
  <% end %>
  <ul v-if="messages.length">
    <li v-for="(msg, index) in messages" :key="index">{{msg}}</li>
  </ul>
</div>

<script>
var formApp = new Vue({
  el: '#form-app',
  data: {
    username: '<%= timetrack.user %>',
    geofence: '<%= timetrack.geofence %>',
    messages: []
  },
  methods: {
    validatesForm(e) {
      this.messages.length = 0;

      if(this.username.trim() == '') {
        this.messages.push('Username can\'t be blank')
      }

      if(!this.geofence) {
        this.messages.push('Please, select the Geofence')
      }

      if(!this.messages.length){
        return true
      }

      e.preventDefault()

    }
  }
})

</script>

app/views/timetracks/all.html.erb
<div class="container">
  <h1>Timetracks</h1>
  <div class="row">
    <p>Click on the timetrack to see on map.</p>
  </div>
  <div class="row">
    <% if @timetracks.any? %>
      <table class="striped highlight responsive-table flow-text">
        <thead>
          <tr>
            <th>User</th>
            <th>Registered at</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th class="hide-on-small-only">Comment</th>
          </tr>
        </thead>
        <tbody>
          <% @timetracks.each do |timetrack| %>
            <tr>
              <td>
                <%= link_to timetrack.user, timetrack, class: 'blue-grey-text text-darken-3' %>
              </td>
              <td>
                <%
                timetrack_date_time = "#{timetrack.created_at.localtime.strftime('%d/%m/%Y')}"
                timetrack_date_time += ' - '
                timetrack_date_time += "#{timetrack.created_at.localtime.strftime('%H:%M %P')}"
                %>
                <%= link_to timetrack_date_time, timetrack, class: 'blue-grey-text text-darken-3' %>
              </td>
              <td><%= link_to timetrack.latitude, timetrack, class: 'blue-grey-text text-darken-3' %></td>
              <td><%= link_to timetrack.longitude, timetrack, class: 'blue-grey-text text-darken-3' %></td>
              <td class="hide-on-small-only">
                <%= link_to timetrack.comment, timetrack, class: 'blue-grey-text text-darken-3' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="flow-text">Nothing found</p>
    <% end %>
  </div>
  <br>
  <div class="row">
    <%= link_to location_timetracks_path, class: 'btn-large waves-effect waves-light red accent-2' do %>
      <i class="material-icons right">add</i> Register Timetrack
    <% end %>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/timetracks/location.html.erb
<div id="app">
  <%= form_for(:timetrack, url: timetracks_register_location_path, local: true, html: { ref: 'form', class: 'test' }) do |f| %>
    <%= f.hidden_field :latitude, 'v-model': 'latitude' %>
    <%= f.hidden_field :longitude, 'v-model': 'longitude' %>
    <%= f.submit 'Send', { class: 'hide' } %>
  <% end %>
  <div class="container blue-grey-text text-lighten-1 center-align">
    <br><br><br>
    <div v-if="!deniedAccess">
      <h1>You must accept location access to proceed</h1>
      <h2 class="flow-text">Please, click on <strong>Allow Location Access</strong> button above.</h2>
    </div>
    <div v-else>
      <h1>You must Reload the page to proceed</h1>
      <h2 class="flow-text">Please, click on the refresh button or press F5.</h2>
    </div>
    <div class="progress" style="margin-top: 200px;">
        <div class="indeterminate"></div>
    </div>
    <br><br><br>
  </div>
</div>

<script>
var app = new Vue({
  el: '#app',
  data: {
    latitude: null,
    longitude: null,
    deniedAccess: false,
  },
  methods: {
    getUserPosition() {
      navigator.geolocation.getCurrentPosition(position => {
        this.latitude = position.coords.latitude
        this.longitude = position.coords.longitude
        this.$nextTick(() => {
          this.$refs.form.submit()
        })
      }, error => {
        this.deniedAccess = true
      })
    }
  },
  mounted() {
    this.getUserPosition()
  }
})

</script>

app/views/timetracks/show.html.erb
<div class="container">
  <h1>Timetrack</h1>

  <% if notice %>
    <div class="card-panel green accent-2 green-text text-darken-4">
      <i class="material-icons medium left">check_circle</i>
      <p class="flow-text"><%= notice %></p>
    </div>
  <% end %>
  <div class="row">
    <div class="col s6">
      <table class="flow-text highlight responsive-table ">
        <tr>
          <td>User:</td>
          <td><strong><%= @timetrack.user %></strong></li></td>
        </tr>
        <tr>
          <td>Geofence:</td>
          <td><strong><%= @timetrack.geofence.description %></strong></li></td>
        </tr>
        <tr>
          <td>Latitude:</td>
          <td><strong><%= @timetrack.latitude %></strong></li></td>
        </tr>
        <tr>
          <td>Longitude:</td>
          <td><strong><%= @timetrack.longitude %></strong></li></td>
        </tr>
        <tr>
          <td>Time:</td>
          <td><strong><%= @timetrack.created_at.localtime.strftime('%H:%M %P') %></strong></li></td>
        </tr>
        <tr>
          <td>Date:</td>
          <td><strong><%= @timetrack.created_at.localtime.strftime('%d/%m/%Y') %></strong></td>
        </tr>
      </table>
    </div>

    <div class="col s6">
      <div id="map" style="width: 600px; height: 400px;"></div>
    </div>
  </div>
  <br><br>
  <div class="row">
    <%= link_to all_timetracks_path, class: 'btn-large waves-effect waves-light blue-grey lighten-4 black-text' do %>
      <i class="material-icons left">arrow_back</i> Back
    <% end %>
  </div>
  <br><br><br>
</div>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>

<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
   integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
   crossorigin=""></script>

<script>
  var mymap = L.map('map').setView([<%= @timetrack.latitude %>, <%= @timetrack.longitude %>], 15);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWF0aHZwIiwiYSI6ImNqeGx5dnU4OTA1d2EzdW8zM3F5YTkzOHYifQ.b-X2rJrUaVOk_qnMk2w9kQ', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 20,
      id: 'mapbox.streets',
      accessToken: 'pk.eyJ1IjoibWF0aHZwIiwiYSI6ImNqeGx5dnU4OTA1d2EzdW8zM3F5YTkzOHYifQ.b-X2rJrUaVOk_qnMk2w9kQ'
  }).addTo(mymap);

  var marker = L.marker([<%= @timetrack.latitude %>, <%= @timetrack.longitude %>]).addTo(mymap);

</script>